version: '3.4'

services:
  app:
    build:
      context: .
      target: runtime
    environment:
      - PORT=$PORT
    ports:
      - 8008:$PORT

  debug:
    build:
      context: .
      target: build
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    entrypoint: /bin/sh

  tests:
    build:
      context: .
      target: test
    volumes:
      - ./test/output:/app/output