version: '3.4'
services:
  app:
    build:
      context: .
      target: runtime
    environment:
      - PORT=8000
    ports:
      - '8000:8000'

  tests:
    build:
      context: .
      target: test
    volumes:
      - ./:/syllable-shaker